version: "3"

services:
  mysql-development:
    image: mysql:5.7.42
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: assignment_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
